2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Configure stats pid to 32316
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Loading settings from C:\Users\vav11\.config\wandb\settings
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Loading settings from D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\wandb\settings
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'Models\\CNN\\dogs_vs_cats\\main.py', 'program_abspath': 'D:\\Backup\\Less Important\\My programs\\Git\\ML\\Models\\CNN\\dogs_vs_cats\\main.py', 'program': 'D:\\Backup\\Less Important\\My programs\\Git\\ML\\Models\\CNN\\dogs_vs_cats\\main.py'}
2024-11-24 23:26:58,571 INFO    MainThread:32316 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:_log_setup():533] Logging user logs to D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\wandb\run-20241124_232658-0sofql8z\logs\debug.log
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:_log_setup():534] Logging internal logs to D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\wandb\run-20241124_232658-0sofql8z\logs\debug-internal.log
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:init():619] calling init triggers
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'CNN', 'dataset': 'Dog_vs_Cats_Kaggle', 'epochs': 20}
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:init():669] starting backend
2024-11-24 23:26:58,572 INFO    MainThread:32316 [wandb_init.py:init():673] sending inform_init request
2024-11-24 23:26:58,575 INFO    MainThread:32316 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-24 23:26:58,575 INFO    MainThread:32316 [wandb_init.py:init():686] backend started and connected
2024-11-24 23:26:58,578 INFO    MainThread:32316 [wandb_init.py:init():781] updated telemetry
2024-11-24 23:26:58,618 INFO    MainThread:32316 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-24 23:26:59,631 INFO    MainThread:32316 [wandb_init.py:init():867] starting run threads in backend
2024-11-24 23:26:59,664 WARNING MainThread:32316 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\wandb\sdk\wandb_init.py", line 910, in init
    run._on_start()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\wandb\sdk\wandb_run.py", line 2496, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\wandb\sdk\interface\interface.py", line 301, in publish_python_packages
    for pkg in working_set:
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\wandb\util.py", line 1928, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\importlib\metadata\__init__.py", line 627, in version
    return self.metadata['Version']
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\importlib\metadata\__init__.py", line 612, in metadata
    return _adapters.Message(email.message_from_string(text))
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\__init__.py", line 38, in message_from_string
    return Parser(*args, **kws).parsestr(s)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\email\feedparser.py", line 237, in _parsegen
    headers.append(line)
KeyboardInterrupt
2024-11-24 23:26:59,673 WARNING MsgRouterThr:32316 [router.py:message_loop():75] message_loop has been closed
