[1,  1000] loss: 0.892
[1,  2000] loss: 0.706
[1,  3000] loss: 0.694
[1,  4000] loss: 0.677
[1,  5000] loss: 0.661
C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\TiffImagePlugin.py:935: UserWarning: Truncated File Read
  warnings.warn(str(msg))
[1,  6000] loss: 0.657
[2,  1000] loss: 0.629
[2,  2000] loss: 0.628
[2,  3000] loss: 0.618
[2,  4000] loss: 0.614
[2,  5000] loss: 0.606
[2,  6000] loss: 0.596
[3,  1000] loss: 0.586
[3,  2000] loss: 0.582
[3,  3000] loss: 0.583
[3,  4000] loss: 0.584
[3,  5000] loss: 0.563
[3,  6000] loss: 0.571
[4,  1000] loss: 0.555
[4,  2000] loss: 0.555
[4,  3000] loss: 0.552
[4,  4000] loss: 0.546
[4,  5000] loss: 0.543
[4,  6000] loss: 0.541
[5,  1000] loss: 0.517
[5,  2000] loss: 0.521
[5,  3000] loss: 0.525
[5,  4000] loss: 0.535
[5,  5000] loss: 0.528
[5,  6000] loss: 0.517
[6,  1000] loss: 0.511
[6,  2000] loss: 0.510
[6,  3000] loss: 0.492
[6,  4000] loss: 0.495
[6,  5000] loss: 0.506
[6,  6000] loss: 0.489
[7,  1000] loss: 0.474
[7,  2000] loss: 0.496
Traceback (most recent call last):
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 48, in <module>
    train_model(
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\train\train.py", line 38, in train_model
    for i, data in enumerate(train_data_loader, 0):
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 245, in __getitem__
    sample = self.loader(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 284, in default_loader
    return pil_loader(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 264, in pil_loader
    return img.convert("RGB")
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\Image.py", line 993, in convert
    self.load()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\ImageFile.py", line 300, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\main.py", line 48, in <module>
    train_model(
  File "D:\Backup\Less Important\My programs\Git\ML\Models\CNN\dogs_vs_cats\train\train.py", line 38, in train_model
    for i, data in enumerate(train_data_loader, 0):
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 245, in __getitem__
    sample = self.loader(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 284, in default_loader
    return pil_loader(path)
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\torchvision\datasets\folder.py", line 264, in pil_loader
    return img.convert("RGB")
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\Image.py", line 993, in convert
    self.load()
  File "C:\Users\vav11\anaconda3\envs\Conda310\lib\site-packages\PIL\ImageFile.py", line 300, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt
